package com.pagestorcontraseña.vistas;

import com.pagestorcontraseña.controlador.CrearContraseñadb;
import com.pagestorcontraseña.controlador.GuardarPersonadb;
import com.pagestorcontraseña.modelTables.ComunicacionCrearContraseña;
import com.pagestorcontraseña.modelTables.ModelTableCrearContraseña;
import com.pagestorcontraseña.modelTables.ModelTableGuardarContraseña;
import com.pagestorcontraseña.modelo.CrearContraseña;
import com.pagestorcontraseña.modelo.GuardarContraseña;
import com.pagestorcontraseña.utilidad.Utilidades;
import java.util.List;
import javax.swing.JOptionPane;

public class PaginaPrincipal extends javax.swing.JFrame implements ComunicacionCrearContraseña {

    private CrearContraseñadb controladorCrearContraseña;
    private GuardarPersonadb controladorGuardarContraseña;
    private CrearContraseña contraEditaEliminada;//Esta ContraseñaEditaEliminada va ser general ya que la voy a ocupar en otras partes del codigo
    private GuardarContraseña guardarContraEditarEliminar;//Esta ContraseñaGuardar va ser general ya que la voy a ocupar en otras partes del codigo
    private ModelTableCrearContraseña modelTableCrearContraseña;
    private ModelTableGuardarContraseña modelTableGuardarContraseña;
    private Utilidades utilidades;

    public PaginaPrincipal() {
        controladorCrearContraseña = new CrearContraseñadb();
        modelTableCrearContraseña = new ModelTableCrearContraseña(controladorCrearContraseña.obtenerContraseñas(), this);
        controladorGuardarContraseña = new GuardarPersonadb();
        modelTableGuardarContraseña = new ModelTableGuardarContraseña(controladorGuardarContraseña.obtenerContraseñas2(), this);
        initComponents();
        setLocationRelativeTo(null);

        utilidades = new Utilidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanelGuardarContraseña = new javax.swing.JPanel();
        btnAvisoSistema = new javax.swing.JButton();
        lbUsuarioSitioWeb = new javax.swing.JLabel();
        lbContraSitioWeb = new javax.swing.JLabel();
        btnGenerarContra = new javax.swing.JButton();
        txtUsuarioCrearContra = new javax.swing.JTextField();
        txtContraseñaCrearContra = new javax.swing.JTextField();
        btnGuardarContra = new javax.swing.JButton();
        btnEditarContra = new javax.swing.JButton();
        btnTraerUltimaContra = new javax.swing.JButton();
        btnEliminarContra = new javax.swing.JButton();
        btnLimpiarCamposContra = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelCrearContraseña = new javax.swing.JPanel();
        lbLetraNombreGuardarContra = new javax.swing.JLabel();
        lbLetraApellidoGuardarContra = new javax.swing.JLabel();
        lbNumeroCedulaGuardarContra = new javax.swing.JLabel();
        lbDiaNacidoGuardarContra = new javax.swing.JLabel();
        lbMesNacidoGuardarContra = new javax.swing.JLabel();
        txtLetraNombreGuardarContra = new javax.swing.JTextField();
        txtLetraApellidoGuardarContra = new javax.swing.JTextField();
        txtNumeroCedulaGuardarContra = new javax.swing.JTextField();
        txtDiaNacidoGuardarContra = new javax.swing.JTextField();
        txtMesNacidoGuardarContra = new javax.swing.JTextField();
        btnBuscarContraseña = new javax.swing.JButton();
        btnCrearContra = new javax.swing.JButton();
        btnEditarContraseña = new javax.swing.JButton();
        btnEliminarContraseña = new javax.swing.JButton();
        btnLimpiarCamposContraseña = new javax.swing.JButton();
        btnTraerContraseña = new javax.swing.JButton();
        jPanelVerContraseñas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelAcercaDe = new javax.swing.JPanel();
        btnQuienesSomos = new javax.swing.JButton();
        jPanelSalirSistema = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("P Á G I N A  P R I N C I P A L");

        btnAvisoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/aviso.png"))); // NOI18N
        btnAvisoSistema.setText("AVISO");
        btnAvisoSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvisoSistemaMouseClicked(evt);
            }
        });

        lbUsuarioSitioWeb.setText("Usuario:");

        lbContraSitioWeb.setText("Contraseña :");

        btnGenerarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/Genradorcontraseñas Pqueño.png"))); // NOI18N
        btnGenerarContra.setText("Generar Contraseña");
        btnGenerarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarContraActionPerformed(evt);
            }
        });

        btnGuardarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/guardar_persona.png"))); // NOI18N
        btnGuardarContra.setText("GUARDAR");
        btnGuardarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarContraActionPerformed(evt);
            }
        });

        btnEditarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/editar_persona.png"))); // NOI18N
        btnEditarContra.setText("EDITAR");
        btnEditarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContraActionPerformed(evt);
            }
        });

        btnTraerUltimaContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/traer_persona.png"))); // NOI18N
        btnTraerUltimaContra.setText("TRAER");
        btnTraerUltimaContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraerUltimaContraActionPerformed(evt);
            }
        });

        btnEliminarContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/eliminar_persona.png"))); // NOI18N
        btnEliminarContra.setText("ELIMINAR");
        btnEliminarContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContraActionPerformed(evt);
            }
        });

        btnLimpiarCamposContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/limpiar.png"))); // NOI18N
        btnLimpiarCamposContra.setText("LIMPIAR CAMPOS");
        btnLimpiarCamposContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposContraActionPerformed(evt);
            }
        });

        jTable2.setModel(modelTableCrearContraseña);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelGuardarContraseñaLayout = new javax.swing.GroupLayout(jPanelGuardarContraseña);
        jPanelGuardarContraseña.setLayout(jPanelGuardarContraseñaLayout);
        jPanelGuardarContraseñaLayout.setHorizontalGroup(
            jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuardarContraseñaLayout.createSequentialGroup()
                        .addComponent(btnGuardarContra)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarContra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTraerUltimaContra)
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminarContra)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarCamposContra)
                        .addGap(68, 68, 68))
                    .addGroup(jPanelGuardarContraseñaLayout.createSequentialGroup()
                        .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGuardarContraseñaLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAvisoSistema)
                                    .addGroup(jPanelGuardarContraseñaLayout.createSequentialGroup()
                                        .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbUsuarioSitioWeb)
                                            .addComponent(lbContraSitioWeb))
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContraseñaCrearContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUsuarioCrearContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGenerarContra)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelGuardarContraseñaLayout.setVerticalGroup(
            jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarContraseñaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAvisoSistema)
                .addGap(37, 37, 37)
                .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuarioSitioWeb)
                    .addComponent(txtUsuarioCrearContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContraSitioWeb)
                    .addComponent(btnGenerarContra)
                    .addComponent(txtContraseñaCrearContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanelGuardarContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarContra)
                    .addComponent(btnLimpiarCamposContra)
                    .addComponent(btnEditarContra)
                    .addComponent(btnEliminarContra)
                    .addComponent(btnTraerUltimaContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane2.addTab("Crear Contraseña", jPanelGuardarContraseña);

        lbLetraNombreGuardarContra.setText("Letra De Tu Nombre:");

        lbLetraApellidoGuardarContra.setText("Letra De Tu Apellido:");

        lbNumeroCedulaGuardarContra.setText("Un Número de tu Cédula:");

        lbDiaNacidoGuardarContra.setText("Día En Que Naciste:");

        lbMesNacidoGuardarContra.setText("Mes En Que Naciste:");

        btnBuscarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/lupa.png"))); // NOI18N
        btnBuscarContraseña.setText("BUSCAR CONTRASEÑA");
        btnBuscarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarContraseñaActionPerformed(evt);
            }
        });

        btnCrearContra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/crearContra.png"))); // NOI18N
        btnCrearContra.setText("CREAR");
        btnCrearContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContraActionPerformed(evt);
            }
        });

        btnEditarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/editar_persona.png"))); // NOI18N
        btnEditarContraseña.setText("EDITAR");
        btnEditarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarContraseñaActionPerformed(evt);
            }
        });

        btnEliminarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/eliminar_persona.png"))); // NOI18N
        btnEliminarContraseña.setText("ELIMINAR");
        btnEliminarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarContraseñaActionPerformed(evt);
            }
        });

        btnLimpiarCamposContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/limpiar.png"))); // NOI18N
        btnLimpiarCamposContraseña.setText("LIMPIAR CAMPOS");
        btnLimpiarCamposContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposContraseñaActionPerformed(evt);
            }
        });

        btnTraerContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/traer_persona.png"))); // NOI18N
        btnTraerContraseña.setText("TRAER");
        btnTraerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraerContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCrearContraseñaLayout = new javax.swing.GroupLayout(jPanelCrearContraseña);
        jPanelCrearContraseña.setLayout(jPanelCrearContraseñaLayout);
        jPanelCrearContraseñaLayout.setHorizontalGroup(
            jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearContraseñaLayout.createSequentialGroup()
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                        .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(btnEditarContraseña)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCrearContra)
                                .addGap(131, 131, 131)))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarContraseña)
                        .addGap(37, 37, 37)
                        .addComponent(btnTraerContraseña))
                    .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addComponent(lbMesNacidoGuardarContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMesNacidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addComponent(lbDiaNacidoGuardarContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiaNacidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbLetraApellidoGuardarContra)
                                    .addComponent(lbNumeroCedulaGuardarContra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroCedulaGuardarContra)
                                    .addComponent(txtLetraApellidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                                .addComponent(lbLetraNombreGuardarContra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLetraNombreGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addComponent(btnBuscarContraseña)))
                .addGap(202, 202, 202))
            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnLimpiarCamposContraseña)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCrearContraseñaLayout.setVerticalGroup(
            jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLetraNombreGuardarContra)
                    .addComponent(txtLetraNombreGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLetraApellidoGuardarContra)
                    .addComponent(txtLetraApellidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNumeroCedulaGuardarContra)
                            .addComponent(txtNumeroCedulaGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelCrearContraseñaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnBuscarContraseña)))
                .addGap(24, 24, 24)
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiaNacidoGuardarContra)
                    .addComponent(txtDiaNacidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMesNacidoGuardarContra)
                    .addComponent(txtMesNacidoGuardarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCrearContraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearContra)
                    .addComponent(btnEditarContraseña)
                    .addComponent(btnEliminarContraseña)
                    .addComponent(btnTraerContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarCamposContraseña)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Guardar Contraseña", jPanelCrearContraseña);

        jTable1.setModel(modelTableGuardarContraseña);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanelVerContraseñasLayout = new javax.swing.GroupLayout(jPanelVerContraseñas);
        jPanelVerContraseñas.setLayout(jPanelVerContraseñasLayout);
        jPanelVerContraseñasLayout.setHorizontalGroup(
            jPanelVerContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerContraseñasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelVerContraseñasLayout.setVerticalGroup(
            jPanelVerContraseñasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerContraseñasLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ver Contraseñas", jPanelVerContraseñas);

        btnQuienesSomos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnQuienesSomos.setText("¿Quienes somos?");
        btnQuienesSomos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuienesSomosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAcercaDeLayout = new javax.swing.GroupLayout(jPanelAcercaDe);
        jPanelAcercaDe.setLayout(jPanelAcercaDeLayout);
        jPanelAcercaDeLayout.setHorizontalGroup(
            jPanelAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAcercaDeLayout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addComponent(btnQuienesSomos)
                .addGap(245, 245, 245))
        );
        jPanelAcercaDeLayout.setVerticalGroup(
            jPanelAcercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcercaDeLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnQuienesSomos)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Acerca De", jPanelAcercaDe);

        javax.swing.GroupLayout jPanelSalirSistemaLayout = new javax.swing.GroupLayout(jPanelSalirSistema);
        jPanelSalirSistema.setLayout(jPanelSalirSistemaLayout);
        jPanelSalirSistemaLayout.setHorizontalGroup(
            jPanelSalirSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jPanelSalirSistemaLayout.setVerticalGroup(
            jPanelSalirSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Salir", jPanelSalirSistema);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pagestorcontraseña/imagenes/admi-contra-pequeño.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("PA - GESTOR DE CONTRASEÑAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 295, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuienesSomosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuienesSomosMouseClicked
        AcercaDE dialog = new AcercaDE();
        dialog.setVisible(true);

    }//GEN-LAST:event_btnQuienesSomosMouseClicked

    private void btnGuardarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarContraActionPerformed

        CrearContraseña crearContraseña = guardarEditarContra();
        if (crearContraseña != null) {
            if (controladorCrearContraseña.crearContraseña(crearContraseña)) {
                JOptionPane.showMessageDialog(rootPane, "Contraseña guardada con éxito en el sistema.");
                limpiarCamposContraseña();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo guardar la contraseña.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnGuardarContraActionPerformed

    private void btnLimpiarCamposContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposContraActionPerformed
        limpiarCamposContraseña();
    }//GEN-LAST:event_btnLimpiarCamposContraActionPerformed

    public CrearContraseña guardarEditarContra() {
        //Utilizamos este Metodo tanto para Guardar como para Editar ya que se repiten los mismo datos
        if (txtUsuarioCrearContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Usuario no tiene datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtUsuarioCrearContra.requestFocus();
            return null;//Me va retornar nulo si se presenta algun error
        }
        if (txtContraseñaCrearContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Contraseña no tiene datos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtContraseñaCrearContra.requestFocus();
            return null;
        }
        CrearContraseña crearContra = new CrearContraseña();
        crearContra.setUsuario(txtUsuarioCrearContra.getText());
        crearContra.setContraseña(txtContraseñaCrearContra.getText());
        return crearContra;

    }


    private void btnEditarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContraActionPerformed
        //Comparamos que la contraseña no sea nula
        if (contraEditaEliminada == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una Contraseña seleccionada para editar.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Comprobamos que la contraseña que estoy editando tenga datos
        CrearContraseña contraseñaEditar = guardarEditarContra();
        if (contraseñaEditar != null) {
            contraseñaEditar.setIdCrearContraseña(contraEditaEliminada.getIdCrearContraseña());
            if (controladorCrearContraseña.editarContraseña(contraseñaEditar)) {
                JOptionPane.showMessageDialog(rootPane, "Contraseña editada con éxito del Sistema.");
                limpiarCamposContraseña();
                contraseñaEditar = null;//Reiniciamos la contraseña para poder editarla
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo editar la Contraseña.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarContraActionPerformed

    private void btnTraerUltimaContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraerUltimaContraActionPerformed
        List<CrearContraseña> obtenerContraseñas = controladorCrearContraseña.obtenerContraseñas();
        contraEditaEliminada = obtenerContraseñas.get(obtenerContraseñas.size() - 1);//Obtengo la ultima contraseña del arreglo
        txtUsuarioCrearContra.setText(contraEditaEliminada.getUsuario());
        txtContraseñaCrearContra.setText(contraEditaEliminada.getContraseña());
    }//GEN-LAST:event_btnTraerUltimaContraActionPerformed

    private void btnEliminarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContraActionPerformed

        if (contraEditaEliminada != null) {
            if (controladorCrearContraseña.eliminarContraseña(contraEditaEliminada)) {
                JOptionPane.showMessageDialog(rootPane, "Contraseña eliminada con éxito del Sistema.");
                limpiarCamposContraseña();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede Eliminar la Contraseña seleccionada.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Contraseña seleccionada para Eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarContraActionPerformed

    private void btnCrearContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContraActionPerformed

        GuardarContraseña guardarGContraseña = guardarEditarContraseña();
        if (guardarGContraseña != null) {
            if (controladorGuardarContraseña.guardarContraseña(guardarGContraseña)) {
                JOptionPane.showMessageDialog(rootPane, "Tú Contraseña se guardó con éxito en el Sistema.");
                limpiarCamposContraseña2();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo guardar tu Contraseña en el Sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_btnCrearContraActionPerformed
    public GuardarContraseña guardarEditarContraseña() { //Metodo para las Validaciones del Sistema Tanto Guardar como Editar

        if (txtLetraNombreGuardarContra.getText().isEmpty()) { //Comprobamos si esta vacio el campo que estamos enviando
            JOptionPane.showMessageDialog(rootPane, "El campo LetraDeTuNombre no tiene ningún Dato.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLetraNombreGuardarContra.requestFocus();//Codigo que sirve para dejar el cursor del mouse en el Campo Vacio
            return null;//Por cuestiones de si tengo algun error
        }
        if (!utilidades.validarLetras(txtLetraNombreGuardarContra.getText().trim())) {//trim sirve para validar que no tenga en cuenta espacios en blanco
            JOptionPane.showMessageDialog(rootPane, "El campo LetraDeTuNombre solo debe contener una Letra.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (txtLetraApellidoGuardarContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo LetraDeTuApellido no tiene ningún Dato.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLetraApellidoGuardarContra.requestFocus();
            return null;
        }
        if (!utilidades.validarLetras(txtLetraApellidoGuardarContra.getText().trim())) {//trim sirve para validar que no tenga en cuenta espacios en blanco
            JOptionPane.showMessageDialog(rootPane, "El campo LetraDeTuApellido solo debe contener una Letra.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (txtNumeroCedulaGuardarContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo UnNumeroDeTúCédula no tiene ningún Dato.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNumeroCedulaGuardarContra.requestFocus();
            return null;
        }
        if (!utilidades.validarNumeros(txtNumeroCedulaGuardarContra.getText().trim())) {//trim sirve para validar que no tenga en cuenta espacios en blanco
            JOptionPane.showMessageDialog(rootPane, "El campo NumeroDeTúCédula solo debe contener Números del 0 al 9.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
//        } else {
//            JOptionPane.showMessageDialog(rootPane, "El campo Un Numero De Tú Cédula es Correcto.");
        }
        if (txtDiaNacidoGuardarContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo DíaEnQueNaciste no tiene ningún Dato.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDiaNacidoGuardarContra.requestFocus();
            return null;
        }
        if (!utilidades.validarNumeros(txtDiaNacidoGuardarContra.getText().trim())) {
            JOptionPane.showMessageDialog(rootPane, "El campo DíaEnQueNaciste solo debe contener Números del 0 al 9.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        if (txtMesNacidoGuardarContra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo MesEnQueNaciste no tiene ningún Dato.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtMesNacidoGuardarContra.requestFocus();
            return null;
        }
        if (!utilidades.validarNumeros(txtMesNacidoGuardarContra.getText().trim())) {
            JOptionPane.showMessageDialog(rootPane, "El campo MesEnQueNaciste solo debe contener Números del 0 al 9.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        GuardarContraseña guardarContraseña = new GuardarContraseña();
        guardarContraseña.setLetraDeTuNombre(txtLetraNombreGuardarContra.getText());
        guardarContraseña.setLetraDeTuApellido(txtLetraApellidoGuardarContra.getText());
        guardarContraseña.setUnNumeroDeTuCedula(txtNumeroCedulaGuardarContra.getText());
        guardarContraseña.setDiaEnQueNaciste(txtDiaNacidoGuardarContra.getText());
        guardarContraseña.setMesEnQueNaciste(txtMesNacidoGuardarContra.getText());
        return guardarContraseña;
    }

    private void btnLimpiarCamposContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposContraseñaActionPerformed
        limpiarCamposContraseña2();
    }//GEN-LAST:event_btnLimpiarCamposContraseñaActionPerformed

    private void btnAvisoSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvisoSistemaMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Recuerda! Dentro del apartado CrearContraseña, puedes guardar Tú Contraseña con cualquier caracter de tu teclado.", "A V I S O", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAvisoSistemaMouseClicked

    private void btnEditarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarContraseñaActionPerformed
        if (guardarContraEditarEliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay Contraseña seleccionada para Editar.", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        GuardarContraseña guardarGCEditar = guardarEditarContraseña();//Comprobamos que los datos lleguen correctos para poder editarlos
        if (guardarGCEditar != null) {
            guardarGCEditar.setIdguardarContraseña(guardarContraEditarEliminar.getIdguardarContraseña());
            if (controladorGuardarContraseña.editarContraseña(guardarGCEditar)) {
                JOptionPane.showMessageDialog(rootPane, "Tú Contraseña se edito con éxito en el Sistema.");
                limpiarCamposContraseña2();
                guardarContraEditarEliminar = null;//Para aqui poder buscar la persona y proceder a editarla
            } else {//Comprobamos que no falle a la hora de hacer la Edicion y vemos cualquier error pertinente
                JOptionPane.showMessageDialog(rootPane, "No se pudo editar tu Contraseña.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarContraseñaActionPerformed

    private void btnTraerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraerContraseñaActionPerformed
        List<GuardarContraseña> obtenerContraseñas2 = controladorGuardarContraseña.obtenerContraseñas2();
        guardarContraEditarEliminar = obtenerContraseñas2.get(obtenerContraseñas2.size() - 1);
        txtLetraNombreGuardarContra.setText(guardarContraEditarEliminar.getLetraDeTuNombre());
        txtLetraApellidoGuardarContra.setText(guardarContraEditarEliminar.getLetraDeTuApellido());
        txtNumeroCedulaGuardarContra.setText(guardarContraEditarEliminar.getUnNumeroDeTuCedula());
        txtDiaNacidoGuardarContra.setText(guardarContraEditarEliminar.getDiaEnQueNaciste());
        txtMesNacidoGuardarContra.setText(guardarContraEditarEliminar.getMesEnQueNaciste());

    }//GEN-LAST:event_btnTraerContraseñaActionPerformed

    private void btnEliminarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarContraseñaActionPerformed

        if (guardarContraEditarEliminar != null) {
            if (controladorGuardarContraseña.eliminarContraseña2(guardarContraEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona Eliminada con éxito del Sistema.");
                limpiarCamposContraseña2();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se pudo Eliminar la Contraseña seleccionada.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Contraseña seleccionada para Eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarContraseñaActionPerformed
    //Metodo para buscar la Contraseña en la BD para posterior poderla Eliminar
    private void btnBuscarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarContraseñaActionPerformed

        GuardarContraseña guardarContraseña = controladorGuardarContraseña.getLetraNombre(txtLetraNombreGuardarContra.getText());
        if (guardarContraseña != null) {
            txtLetraApellidoGuardarContra.setText(guardarContraseña.getLetraDeTuApellido());
            txtNumeroCedulaGuardarContra.setText(guardarContraseña.getUnNumeroDeTuCedula());
            txtDiaNacidoGuardarContra.setText(guardarContraseña.getDiaEnQueNaciste());
            txtMesNacidoGuardarContra.setText(guardarContraseña.getMesEnQueNaciste());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Contraseña no encontrada en el Sistema.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtLetraNombreGuardarContra.setText("");
            txtLetraNombreGuardarContra.requestFocus();
        }


    }//GEN-LAST:event_btnBuscarContraseñaActionPerformed

    private void btnGenerarContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarContraActionPerformed
        GeneradorContraseñas dialog = new GeneradorContraseñas();
        dialog.setVisible(true);
    }//GEN-LAST:event_btnGenerarContraActionPerformed
    private void limpiarCamposContraseña() {
        txtUsuarioCrearContra.setText("");
        txtContraseñaCrearContra.setText("");
    }

    private void limpiarCamposContraseña2() {
        txtLetraNombreGuardarContra.setText("");
        txtLetraApellidoGuardarContra.setText("");
        txtNumeroCedulaGuardarContra.setText("");
        txtDiaNacidoGuardarContra.setText("");
        txtMesNacidoGuardarContra.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvisoSistema;
    private javax.swing.JButton btnBuscarContraseña;
    private javax.swing.JButton btnCrearContra;
    private javax.swing.JButton btnEditarContra;
    private javax.swing.JButton btnEditarContraseña;
    private javax.swing.JButton btnEliminarContra;
    private javax.swing.JButton btnEliminarContraseña;
    private javax.swing.JButton btnGenerarContra;
    private javax.swing.JButton btnGuardarContra;
    private javax.swing.JButton btnLimpiarCamposContra;
    private javax.swing.JButton btnLimpiarCamposContraseña;
    private javax.swing.JButton btnQuienesSomos;
    private javax.swing.JButton btnTraerContraseña;
    private javax.swing.JButton btnTraerUltimaContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelAcercaDe;
    private javax.swing.JPanel jPanelCrearContraseña;
    private javax.swing.JPanel jPanelGuardarContraseña;
    private javax.swing.JPanel jPanelSalirSistema;
    private javax.swing.JPanel jPanelVerContraseñas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbContraSitioWeb;
    private javax.swing.JLabel lbDiaNacidoGuardarContra;
    private javax.swing.JLabel lbLetraApellidoGuardarContra;
    private javax.swing.JLabel lbLetraNombreGuardarContra;
    private javax.swing.JLabel lbMesNacidoGuardarContra;
    private javax.swing.JLabel lbNumeroCedulaGuardarContra;
    private javax.swing.JLabel lbUsuarioSitioWeb;
    private javax.swing.JTextField txtContraseñaCrearContra;
    private javax.swing.JTextField txtDiaNacidoGuardarContra;
    private javax.swing.JTextField txtLetraApellidoGuardarContra;
    private javax.swing.JTextField txtLetraNombreGuardarContra;
    private javax.swing.JTextField txtMesNacidoGuardarContra;
    private javax.swing.JTextField txtNumeroCedulaGuardarContra;
    private javax.swing.JTextField txtUsuarioCrearContra;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickCrearCrontraseña(CrearContraseña c) {
        txtUsuarioCrearContra.setText(c.getUsuario());
        txtContraseñaCrearContra.setText(c.getContraseña());
    }

    @Override
    public void clickGuardarCrontraseña(GuardarContraseña g) {
        txtLetraNombreGuardarContra.setText(g.getLetraDeTuNombre());
        txtLetraApellidoGuardarContra.setText(g.getLetraDeTuApellido());
        txtNumeroCedulaGuardarContra.setText(g.getUnNumeroDeTuCedula());
        txtDiaNacidoGuardarContra.setText(g.getDiaEnQueNaciste());
        txtMesNacidoGuardarContra.setText(g.getMesEnQueNaciste());
    }
}
